# https://istio.io/latest/docs/ops/integrations/certmanager/
# https://cert-manager.io/docs/usage/certificate/

# The Certificate should be created in the same namespace as the
# istio-ingressgateway deployment

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: httpbin-ingress-cert
  namespace: istio-system
spec:
  secretName: httpbin-ingress-cert
  issuerRef:
    name: letsencrypt-prod # kubectl get clusterissuer -A
    kind: ClusterIssuer
  dnsNames:
  - REDACTED
