apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-httpbin
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx-internal"
spec:
  rules:
  - host: test.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: httpbin
          servicePort: 8000
