apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: internal-nginx

bases:
- ../../base

patches:
- path: httpbin-service-lb-change.yaml
  target:
    kind: Service
    name: httpbin

resources:
- namespace.yaml
- ingress.yaml
