apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpapp
      version: v1
  template:
    metadata:
      labels:
        app: phpapp
        version: v1
    spec:
      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-config
      - name: shared-files
        emptyDir: {}
      containers:
      - image: psibi/cake-php-demo:v1.0.7
        securityContext:
          runAsUser: 1000
        imagePullPolicy: IfNotPresent
        name: phpapp
        volumeMounts:
        - name: shared-files
          mountPath: /application
          readOnly: false
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "cp -r /app/* /application"]
      - image: nginx:1.23.1
        name: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: shared-files
          mountPath: /application
          readOnly: false
