kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {
    }
    http {
      server {
        listen 80 default_server;
        listen [::]:80 default_server;

        # Set nginx to serve files from the shared volume!
        root /var/www-data/webroot;
        index index.php;
        server_name _;

        location / {
          try_files $uri $uri/ /index.php?$args;
        }
        location ~ \.php$ {
          try_files $uri =404;
          include fastcgi_params;
          fastcgi_pass 127.0.0.1:9000;
          fastcgi_intercept_errors on;

          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

        }
      }
    }
