apiVersion: v1
kind: Namespace
metadata:
  name: base-app
  labels:
    istio-injection: enabled
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: peer
spec:
  mtls:
    mode: STRICT
