apiVersion: v1
kind: Service
metadata:
  name: prometheus-example-app
  labels:
    app.kubernetes.io/name: prometheus-example-app
spec:
  ports:
  - name: web
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/name: prometheus-example-app
