apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: base-app

bases:
- ../../base

resources:
  - namespace.yaml
  - httpbin-ingress.yaml

patches:
- path: httpbin-service-lb-change.yaml
  target:
    kind: Service
    name: httpbin
