apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prod
  template:
    metadata:
      labels:
        app: prod
    spec:
      containers:
      - image: docker.io/argoproj/rollouts-demo:yellow
        imagePullPolicy: IfNotPresent
        name: prod
        ports:
        - containerPort: 8000
  strategy:
    canary:
      # Reference to a Service which the controller will update to point to the canary ReplicaSet
      canaryService: canary
      # Reference to a Service which the controller will update to point to the stable ReplicaSet
      stableService: prod
      trafficRouting:
        nginx:
          # Reference to an Ingress which has a rule pointing to the stable service (e.g. rollouts-demo-stable)
          # This ingress will be cloned with a new name, in order to achieve NGINX traffic splitting.
          stableIngress: prod-ingress
          additionalIngressAnnotations:   # optional
            canary-by-header: X-Canary
      steps:
      - setWeight: 20
      - pause: {}
