# List all recipies
default:
    just --list --unsorted

# Build image
build-image:
    docker build . -t psibi/ubuntu-20.04:v1.0.0

# Push image
push-image:
    docker push psibi/ubuntu-20.04:v1.0.0
