apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: httpbin-tls
spec:
  backendType: azureKeyVault
  keyVaultName: tempCert
  template:
    type: kubernetes.io/tls
  data:
    - key: "testCert"
      name: tls.crt
      isBinary: true
    - key: "testKey"
      name: tls.key
      isBinary: true
