apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-httpbin
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - READACTED # Put public ip address 172.217.167.142 or the host DNS
    secretName: httpbin-tls
  rules:
  - host: REDACTED
    http:
      paths:
      - path: /
        backend:
          serviceName: httpbin
          servicePort: 8000
