apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-httpbin
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: httpbin
          servicePort: 8000
