apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: canary

bases:
- ../istio

patchesStrategicMerge:
- gateway.yaml
- virtualservice.yaml
- service.yaml

resources:
- websocket.yaml
- destination_rule.yaml
