apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: base-app

bases:
- ../../base

patches:
- path: httpbin-service-lb-change.yaml
  target:
    kind: Service
    name: httpbin
- path: pv-claim.yaml
  target:
    kind: Deployment
    name: httpbin

resources:
- namespace.yaml
- pv.yaml
