version: "3.9"
services:
  mysql:
    container_name: mysql-app
    image: mysql:8
    environment:
      MYSQL_DATABASE: 'cakephp'
      MYSQL_USER: 'cakephp'
      MYSQL_PASSWORD: 'cakephp'
      MYSQL_ROOT_PASSWORD: 'cakephp'
    expose:
    - "3306"
  ubuntu:
    container_name: ubuntu-mysql
    image: psibi/ubuntu-20.04:v1.0.0
    tty: true
    depends_on:
    - mysql
