version: "3.9"  # optional since v1.27.0
services:
  web:
    container_name: web-php
    image: psibi/php-demo:v1.0.0
    ports:
      - "9000:9000"
  nginx:
    container_name: nginx
    image: nginx:1.23.1
    ports:
      - "8000:80"
    volumes:
      - ./hello.php:/app/hello.php
      - ./etc/nginx.conf:/etc/nginx/nginx.conf
